name: Daily News

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send-news:
    runs-on: ubuntu-24.04
    timeout-minutes: 300

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with caching
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run emails with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 10
          retry_wait_seconds: 1800
          retry_on: error
          retry_on_exit_code: 111
          command: python run_send.py --email
