name: Daily News

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

permissions:
  contents: read

# env:
  # UV_SYSTEM_PYTHON: 1

jobs:
  send-news:
    runs-on: ubuntu-24.04
    timeout-minutes: 330

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: 3.12

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Run emails with retry
        uses: nick-fields/retry@v3
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          timeout_minutes: 5
          max_attempts: 10
          retry_wait_seconds: 1800
          retry_on: error
          retry_on_exit_code: 111
          command: uv run run_send.py --email
