name: Daily Reminders

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send-news:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with caching
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run reminders
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ML_2025_REMINDER_LINK: ${{ vars.ML_2025_REMINDER_LINK }}
          ML_2025_2_REMINDER_LINK: ${{ vars.ML_2025_2_REMINDER_LINK }}
        run: python run_send.py --reminder
