name: Retry Test

on:
  workflow_dispatch:

jobs:
  retry-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run test script with retry
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          retry_wait_seconds: 5
          retry_on: error
          retry_on_exit_code: 111
          command: python retry_test.py
